services:
  # server:
  #   build: .
  #   hostname: server
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - PGHOST=db
  #     - PGPASSWORD=1234
  #     - PGUSER=postgres
  #     - PGDATABASE=postgres
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=1234
  #     - SESSION_SECRET=sus
  #     - NODE_ENV=dev
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis-stack:
  #       condition: service_healthy

  redis-stack:
    image: redis/redis-stack
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass 1234"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a 1234 ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: "db:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "1234"
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ahmed.hesham.farag@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      # - SCRIPT_NAME=/pgadmin/
    ports:
      - 85:80
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./rules:/rules
      # - ./data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.external-url=/prometheus/"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: /grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  # alloy:
  #   image: grafana/alloy
  #   hostname: alloy
  #   restart: unless-stopped
  #   volumes:
  #     - ./configs/alloy:/etc/alloy/
  #     # - /home/ahmed/.kube/config:/config
  #   ports:
  #     - 12345:12345
  #   command: >
  #     run
  #     --server.http.listen-addr=0.0.0.0:12345
  #     --storage.path=/var/lib/alloy/data
  #     /etc/alloy

  loki:
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100

  tempo:
    image: grafana/tempo
    restart: unless-stopped
    hostname: tempo
    ports:
      - 3200:3200
      - 4317:4317
      - 9095:9095
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    command:
      - "-target=all"
      - "-config.file=/etc/tempo.yaml"

  nginx:
    image: nginx
    ports:
      - 8000:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/ca:/ca
    depends_on:
      pgadmin:
        condition: service_started
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
      loki:
        condition: service_started

  kafka:
    image: apache/kafka:latest
    restart: unless-stopped

    ports:
      - 9092:9092

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://192.168.1.25:9092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    post_start:
    - command:
        - /bin/sh
        - -c
        - |
          until /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:29092 \
            --list >/dev/null 2>&1; do
            echo "Waiting for Kafka..."
            sleep 2
          done

          echo "Kafka is ready. Creating topic..."

          /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:29092 \
            --create \
            --if-not-exists \
            --topic url-views \
            --partitions 1 \
            --replication-factor 1


  kafka-ui:
    image: redpandadata/console:latest
    restart: unless-stopped
    ports:
      - 9025:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_BROKERS: "kafka:29092"

  jobmanager:
    build: 
      dockerfile: flink.Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    post_start:
      - command: bin/sql-client.sh -f /pipeline.sql
        user: flink
    volumes:
      - ./configs/flink/pipeline.sql:/pipeline.sql:ro
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started


  taskmanager:
    build: 
      dockerfile: flink.Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
  
  # sql-client:
  #   build: 
  #     dockerfile: flink.Dockerfile
  #   depends_on:
  #     - jobmanager
  #   command: bin/sql-client.sh
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       rest.address: jobmanager